apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-08-05T00:39:04Z"
  labels:
    app: jupyter-app
  name: jupyter-svc
  namespace: jupyter
  resourceVersion: "1371"
  uid: 16600d5e-30b6-478c-921f-e54d862f5331
spec:
  clusterIP: 10.103.140.0
  clusterIPs:
  - 10.103.140.0
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30000
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter-pods
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
