apiVersion: v1
kind: Endpoints
metadata:
  name: my-endpoints-service
subsets:
  - addresses:
      - ip: 46.246.29.69
      - ip: 10.244.5.166
      - ip: 10.244.5.167 
    ports: 
      - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-endpoints-service
spec:
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 80
