apiVersion: v1
kind: Secret
metadata: 
  name: secret-basci-auth
type: kubernetes.io/basic-auth
data:
  username: YWRtaW4K
  password: UGFzcy0xMjMK
  extra-key: UGFzcy0xMjMK

stringData:
  extra2: value2