apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cj
spec:
  parallelism: 5
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 10
  schedule: "* * * * *"
  jobTemplate:
    spec:
      completions: 10
      completionMode: "Indexed"
      template:
        spec:
          containers:
          - name: my-container-busybox
            image: busybox
            command: ["/bin/sh", "-c", "./script.sh"]
          restartPolicy: Never
        